### ISSUE TITLE
"Internal Pandora error" due to invalid Pandora certificate

### ISSUE THREAD

**Issue by cybiant** [HermesApp/Hermes#337] opened 2018-06-18 13:07 UTC
Just reporting that I receive the message "An error has occurred with Pandora | Try Again | Internal Pandora error".  Trying to use Hermes with OSX Mojave Beta.

**Comment by dsemb** [comment] 2018-07-03 15:34
Same issue.

**Comment by Kenshin0120** [comment] 2018-07-10 03:33
Same issue...

**Comment by JefeRyan** [comment] 2018-07-16 05:47
Same issue.

**Comment by jjisawesome** [comment] 2018-07-17 18:13
same

**Comment by stave** [comment] 2018-07-18 21:38
@jjisawesome An easy hack is to disable SSL.. Change Pandora.m:818 to `[request tls] ? "" : "",`.

It's certainly not the RIGHT answer, but hey, it makes my music play again.

**Comment by jjisawesome** [comment] 2018-07-19 01:29
fyi, most of dark mode is supported with just that fix (icons need updating tho)
![image](https://user-images.githubusercontent.com/14036709/42916126-7ee061c6-8ab8-11e8-8e24-e6d5f4a232ae.png)

**Comment by nriley** [comment] 2018-07-19 01:47
BTW folks — as it says on the front page, this project is unmaintained. I am the only former developer even looking at things from time to time, and I am only getting busier in my work, so I don't see much changing any time soon.

If anyone wants to work on the streaming issues or some dark mode-compatible icons or both, just start fixing stuff and file pull requests.  If others don't pitch in, Hermes will continue to die a slow death.

(From the screenshot above It also looks like the drawer, which is a deprecated UI element in any case, essentially has no dark mode appearance so it'll look out of place no matter what.  It might make sense to switch the station list/history to popovers, unless whoever does the work has a better idea.)

**Comment by jjisawesome** [comment] 2018-07-19 04:04
Starting in September, I will be able to devote some time to things like icon design and learning the basics of app development. I am still pretty new when it comes to coding, but I don't think it will be too hard for me to learn how to wrangle the ui elements.

**Comment by dsemb** [comment] 2018-07-19 22:17
I have not worked in Xcode before. The closest is some Terminal, Filemaker, and Access work. I am playing with Xcode now. Any resources you can suggest so that I can update and possibly help to maintain (in the future) Hermes. It is probably my favorite application I have installed and I will try to find time to maintain it.

**Comment by oey192** [comment] 2018-08-06 17:08
FYI I am having the same problem as described in this thread (Internal Pandora Error) on High Sierra 10.13.6. I'm guessing whatever causes this bug in Mojave was also included in the ".6" release of High Sierra

**Comment by stave** [comment] 2018-08-06 17:33
Better workaround: Manually trust the tuner.pandora.com certificate. Follow the directions on [Apple's KB article for trusting certificates](https://support.apple.com/kb/ph25443?locale=en_US), which I've kind of summarized here:

Point Safari to https://tuner.pandora.com. In the warning that pops up, pick "view the certificate," click on *.pandora.com. Drag the large certificate icon to the desktop. Double click it. Add it to the "login" certificate. Double click it in Keychain Access. Expand the Trust section. Change Secure Sockets Layer (SSL) from "no value specified" to "Always Trust". Launch Hermes. Enjoy music.

Pandora's undocumented API that Hermes uses is at tuner.pandora.com, and it has an old certificate from GeoTrust, which is owned by Symantec. Apple, Google, and others aren't [trusting these old certs](https://support.apple.com/en-us/HT208860) anymore, because Symantec [messed up pretty bad](https://security.googleblog.com/2017/09/chromes-plan-to-distrust-symantec.html) in its role as a root certificate authority. Until Pandora gets a better cert, your only options are to 1) stop using SSL or 2) trust their old cert for this specific purpose.

**Comment by dlindquist** [comment] 2018-08-06 19:28
Same here - thanks @stave !

**Comment by dsemb** [comment] 2018-08-06 20:33
Heck Yes!


Take care,

Dustin




Dustin Semb, PhD
509.710.4186
dsemb@icloud.com

PS Please consider the environment before printing this e-mail

**Comment by fperez** [comment] 2018-08-07 03:11
Quick note: in my case Safari didn't pop up any warnings, instead giving me only a `Forbidden - you don't have permission to access / on this server` page.  

If that happens to you, click on the padlock icon on the URL bar, and the dialog with a "Show Certificate" button will appear.  You can then follow @stave's instructions above.

**Comment by canturkisci** [comment] 2018-08-24 16:40
Thank you @stave works for me as well. Have been trying to figure this for couple of weeks.

**Comment by darlinjgray** [comment] 2018-08-30 16:40
Thank you @stave! Worked like a charm. :)

**Comment by nriley** [comment] 2018-09-08 01:15
@tomvoss Yes! tuner.pandora.com (non-Pandora One users) seems to be fixed as of today.  internal-tuner.pandora.com (Pandora One) is not, but I may be able to figure out a way around it without rewriting networking. Will look into it more this weekend.

**Comment by nriley** [comment] 2018-09-10 21:14
It does so automatically - it checks if you have a Pandora One account
and switches over.  But last I checked the certificate isn't updated
so you may still be getting errors.

**Comment by Djspaceg** [comment] 2018-09-19 01:30
> fyi, most of dark mode is supported with just that fix (icons and drawer need updating tho)
> ![image](https://user-images.githubusercontent.com/14036709/42916126-7ee061c6-8ab8-11e8-8e24-e6d5f4a232ae.png)

Hi guys,
I actually made the current set of icons, so I'd be happy to make a light version too, for the dark skin mode. In fact, the work is even sitting on my github repo: https://github.com/Djspaceg/hermes-images

**Comment by jpkossin** [comment] 2018-10-04 19:13
Thank you @stave, @fperez, and @nriley. I needed all three of your comments to make this work for me. As a Pandora One subscriber, I had to follow @stave's steps but with the certificate for https://internal-tuner.pandora.com. It did not work for me by trusting the https://tuner.pandora.com certificate. Perseverance paid off on this one...

**Comment by Djspaceg** [comment] 2018-10-04 20:20
I had the same initial issue as @jpkossin, but I had not persevered, giving up. I did try @jpkossin's steps and those _did_ work for me. So I'm all good now! Thanks for commenting!

**Comment by antoncohen** [comment] 2018-10-30 18:29
https://internal-tuner.pandora.com/ now has a certificate from DigiCert, so it is working. I think this issue can be closed.

**Comment by nriley** [comment] 2018-10-30 21:41
Confirmed. I’ll remove the workaround when I get a chance.

**Closed by nriley** 2018-10-30 21:41 UTC

**Comment by SimonSaysSmile** [comment] 2018-12-18 00:04
Could someone walk me through on how to get dark-mode for Hermes? Thank you to everyone who contributed to this issue thread! I'm so grateful that I can use Hermes again :).
