### ISSUE TITLE
Having problems connecting when app is opened. What api/server do we connect to?

### ISSUE THREAD

**Issue by shaun10** [HermesApp/Hermes#247] opened 2015-10-22 18:34 UTC
I know the project has a lot of issues and is abandoned. My issue occurs when the app is first opened on OS X 10.11 El Capitan. Does anyone know if Pandora changed something in their API? Possible work around or areas in the code to focus on for fix? Wondering if there is a history of the issue also.

![screen shot 2015-10-22 at 11 33 43 am](https://cloud.githubusercontent.com/assets/7233643/10674605/c4bea1b6-78b0-11e5-8127-a0077774e652.png)

**Comment by nriley** [comment] 2016-05-08 23:06
Seems a duplicate of #259.

**Closed by nriley** 2016-05-08 23:06 UTC
